---
version: '3'
services:
  web:
    build: .
    ports: [80:80]
    volumes: [.:/usr/src/app, /usr/src/app/node_modules]
    environment: [NODE_ENV=development]
  nginx:
    image: nginx:1.17-alpine
    volumes: [./nginx.conf:/etc/nginx/nginx.conf]
    ports: [80:80]
