# Auto-generated by Cloud Code AI

# Use Ubuntu as base image
FROM ubuntu:latest

# Update the Ubuntu
RUN apt-get update

# Install Node.js
RUN apt-get install -y nodejs

# Install npm
RUN apt-get install -y npm

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ 'npm', 'start' ]